### ISSUE TITLE
Sort by "free rooms near you"

### ISSUE THREAD

**Issue by Androz2091** [antoninfaure/occupancy-front#1]
Thank you for the new version, it's awesome! We are a group of friends using it every day.

It would be really useful to be able to open the website, choose a time range (same as we do right now), and enable location to sort the rooms based on the coordinates we are currently at.

I don't know whether there exists a list of coordinates for each room but I guess that it does because the feature exists on the Campus app.

What do you think?

**Comment by antoninfaure** [comment]
Done x)
